- hosts: Dev
  tasks: 
     - name: delete old deployment
       shell: kubectl delete -f /root/k8s/Deployment.yml
     - name: delete old service
       shell: kubectl delete -f /root/k8s/Service.yml
     - name: create new deployment
       shell: kubectl apply -f /root/k8s/Deployment.yml
     - name: create new service
       shell: kubectl apply -f /root/k8s/Service.yml
