- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /k8s/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /k8s/Service.yml
     - name: create new deployment
       command: kubectl apply -f /k8s/Deployment.yml
     - name: create new service
       command: kubectl apply -f /k8s/Service.yml
